# Generated by Django 5.1.1 on 2025-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemImg', models.CharField(max_length=500)),
                ('ItemName', models.CharField(max_length=32)),
                ('ItemDescription', models.CharField(max_length=750)),
                ('ItemStackType', models.CharField(max_length=32)),
                ('ItemTier', models.CharField(max_length=32)),
                ('ItemActPass', models.CharField(max_length=32)),
                ('Cooldown', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonsterImg', models.CharField(max_length=500)),
                ('MonsterName', models.CharField(max_length=32)),
                ('MonsterHealth', models.IntegerField(max_length=50000)),
                ('MonsterDamage', models.CharField(max_length=8)),
                ('MonsterHPRegen', models.CharField(max_length=8)),
                ('MonsterArmour', models.CharField(max_length=32)),
                ('MonsterSpeed', models.CharField(max_length=32)),
                ('Class', models.CharField(max_length=32)),
                ('MonsterType', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurvivorImg', models.CharField(max_length=500)),
                ('SurvivorName', models.CharField(max_length=32)),
                ('SurvivorHealth', models.CharField(max_length=32)),
                ('SurvivorDamage', models.CharField(max_length=32)),
                ('SurvivorHPRegen', models.CharField(max_length=32)),
                ('Class', models.CharField(max_length=32)),
                ('SurvivorArmour', models.CharField(max_length=32)),
                ('SurvivorSpeed', models.CharField(max_length=32)),
                ('SurvivorMass', models.CharField(max_length=32)),
                ('SurvivorDescription', models.CharField(max_length=750)),
            ],
        ),
    ]
