# Generated by Django 5.1.1 on 2025-11-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROR2_Wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Cooldown',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterHealth',
            field=models.IntegerField(),
        ),
    ]
