# Generated by Django 5.1.1 on 2025-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROR2_Wiki', '0002_alter_item_cooldown_alter_monster_monsterhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Cooldown',
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemActPass',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemStackType',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemTier',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='Class',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterArmour',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterDamage',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterHPRegen',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterHealth',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterType',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='Class',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorArmour',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorDamage',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorDescription',
            field=models.SlugField(max_length=750),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorHPRegen',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorHealth',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorMass',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorSpeed',
            field=models.SlugField(max_length=32),
        ),
    ]
