# Generated by Django 5.1.1 on 2025-11-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROR2_Wiki', '0003_alter_item_cooldown_alter_item_itemactpass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemDescription',
            field=models.SlugField(max_length=75),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemImg',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemName',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterImg',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterName',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterSpeed',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorImg',
            field=models.SlugField(max_length=500),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorName',
            field=models.SlugField(max_length=32),
        ),
    ]
