# Generated by Django 5.1.1 on 2025-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROR2_Wiki', '0005_alter_item_cooldown_alter_item_itemactpass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='survivor',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemName',
            field=models.SlugField(max_length=124, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterName',
            field=models.SlugField(max_length=74, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorName',
            field=models.SlugField(max_length=74, primary_key=True, serialize=False),
        ),
    ]
