# Generated by Django 5.1.1 on 2025-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROR2_Wiki', '0006_remove_item_id_remove_monster_id_remove_survivor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Cooldown',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemActPass',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemDescription',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemImg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemName',
            field=models.CharField(max_length=124, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemStackType',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemTier',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='Class',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterArmour',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterDamage',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterHPRegen',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterHealth',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterImg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterName',
            field=models.CharField(max_length=74, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterSpeed',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='monster',
            name='MonsterType',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='Class',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorArmour',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorDamage',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorDescription',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorHPRegen',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorHealth',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorImg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorMass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorName',
            field=models.CharField(max_length=74, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='SurvivorSpeed',
            field=models.CharField(max_length=74),
        ),
    ]
